
name=input("Hi, What your name?")
color=input(f"hola {name}, what is your favorite color?")
print("Wow! you are cool like the color!")
input("")
food=input("Hey whats your favorite food")
print("that pretty aura!")
movie=input("whats your favorite movie?")
print("That one is pretty cool dude!")
input("")
print("my favorite color is red")
input("")
print("My favorite food is pasta")
input("")
print("My favorite movie is BMS")